use Northwind_turkce

--TARÝH FONKSÝYONLARI

--GETDATE : Bu günün tarihini verir
select GETDATE()
--DATEADD VERÝLEN TARÝHE VERÝLDÝÐÝ KADAR GÜN AY YIL EKLER
SELECT DATEADD(DAY,999,GETDATE())
SELECT DATEADD(MONTH,999,GETDATE())
SELECT DATEADD(YEAR,999,GETDATE())
--DATEDIFF ==> ÝKÝ TARÝH ARASINDA GÜNÜ AYI VEYA YILI HESAPLAR
SELECT DATEDIFF(DAY,'05.09.1990',GETDATE())--verilen iki tarih arasýnda bu kdar gün vardýr
select DATEDIFF(MONTH,'05.09.1990',GETDATE())--bu kadar ay
select DATEDIFF(YEAR,'05.09.1990',GETDATE())-- bu kadar yýl vardýr

--DATEPART VERÝLEN TARÝHÝN HAFTANIN AYIN YAHUT YILIN KAÇINCI GÜNÜ OLDUÐUNU HESAPLAR
SELECT DATEPART(DW,GETDATE())
SELECT DATEPART(MONTH,GETDATE())
SELECT DATEPART(DAY,GETDATE())